import "~/styles/globals.css";
import { GeistSans } from "geist/font/sans";
import { Sidebar } from "~/components/ui/sidebar";
import { Providers } from "./providers";

// export const metadata: Metadata = {
//   title: "Create T3 App",
//   description: "Generated by create-t3-app",
//   icons: [{ rel: "icon", url: "/favicon.ico" }],
// };

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex h-screen">
        <Sidebar name="FinLexa" />
        <main className="flex-1 overflow-auto p-6">{children}</main>
      </body>
    </html>
  );
}
